export default {
    ACTIONS: {
        PURCHASE_START: 'PURCHASE_BURGER_START',
        PURCHASE_SUCCESS: 'PURCHASE_BURGER_SUCCESS',
        PURCHASE_FAIL: 'PURCHASE_BURGER_FAIL',
        PURCHASE_INIT: 'PURCHASE_INIT'
    }
}